// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_JA09WddezqmNYENPB6BEnPzh1UZEp2A',
    appId: '1:785230319460:web:087d81b5d2ad3f13f87471',
    messagingSenderId: '785230319460',
    projectId: 'todo2-254af',
    authDomain: 'todo2-254af.firebaseapp.com',
    storageBucket: 'todo2-254af.appspot.com',
    measurementId: 'G-YR0QM10JVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlpRoJ5HSEKmuxF3G-DmYgaRE0g4T4XH0',
    appId: '1:785230319460:android:09bb46880d7264b8f87471',
    messagingSenderId: '785230319460',
    projectId: 'todo2-254af',
    storageBucket: 'todo2-254af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOMBPtFXw_UikAJH5Lt_wuwYevXOX68m8',
    appId: '1:785230319460:ios:2acd62e38de31cd3f87471',
    messagingSenderId: '785230319460',
    projectId: 'todo2-254af',
    storageBucket: 'todo2-254af.appspot.com',
    iosClientId: '785230319460-n972d6lsec1auvo61niq3tpuh5hiigth.apps.googleusercontent.com',
    iosBundleId: 'com.example.class2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOMBPtFXw_UikAJH5Lt_wuwYevXOX68m8',
    appId: '1:785230319460:ios:2acd62e38de31cd3f87471',
    messagingSenderId: '785230319460',
    projectId: 'todo2-254af',
    storageBucket: 'todo2-254af.appspot.com',
    iosClientId: '785230319460-n972d6lsec1auvo61niq3tpuh5hiigth.apps.googleusercontent.com',
    iosBundleId: 'com.example.class2',
  );
}
