// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy-icl7nuYeqXflNtG6W4PoBc8x7c888Q',
    appId: '1:563977004560:web:dd14d6b9284e2be23dcc95',
    messagingSenderId: '563977004560',
    projectId: 'fir-classes-3a31b',
    authDomain: 'fir-classes-3a31b.firebaseapp.com',
    storageBucket: 'fir-classes-3a31b.appspot.com',
    measurementId: 'G-PRS04EP35C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBId9-_2gs4e_JPra1t4P3UDSUdGfnWDu0',
    appId: '1:563977004560:android:88cf464dd043aea13dcc95',
    messagingSenderId: '563977004560',
    projectId: 'fir-classes-3a31b',
    storageBucket: 'fir-classes-3a31b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC25wPbUe3n2g6wcBNnRTIU31mqVj4UD28',
    appId: '1:563977004560:ios:7f4e4c1f1ebded403dcc95',
    messagingSenderId: '563977004560',
    projectId: 'fir-classes-3a31b',
    storageBucket: 'fir-classes-3a31b.appspot.com',
    iosClientId: '563977004560-a0cfdr20k2hihbdrbl1dccff9d8irbil.apps.googleusercontent.com',
    iosBundleId: 'com.example.class1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC25wPbUe3n2g6wcBNnRTIU31mqVj4UD28',
    appId: '1:563977004560:ios:7f4e4c1f1ebded403dcc95',
    messagingSenderId: '563977004560',
    projectId: 'fir-classes-3a31b',
    storageBucket: 'fir-classes-3a31b.appspot.com',
    iosClientId: '563977004560-a0cfdr20k2hihbdrbl1dccff9d8irbil.apps.googleusercontent.com',
    iosBundleId: 'com.example.class1',
  );
}
